# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
