# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='adhaarId',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
