# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170307_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='adhaarId',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
