# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-20 04:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20170307_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesinFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=b'')),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('desc', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserFolders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='filesinfolder',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserFolders'),
        ),
    ]
