# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-24 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170420_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfolders',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
