# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-24 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170424_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=b'')),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('desc', models.CharField(blank=True, max_length=128)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserFolders')),
            ],
        ),
        migrations.RenameModel(
            old_name='FilesinFolder',
            new_name='PrescriptionFiles',
        ),
    ]
