# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_examplemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionfiles',
            name='file',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testfiles',
            name='file',
            field=models.TextField(),
        ),
    ]
